# Base Kustomization - No version-specific configuration
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: stack-lifecycle-deploy
  managed-by: kustomize

resources:
  # Infrastructure
  - mysql.yml
  - mysql-service.yml
  - redis.yml
  - redis-service.yml
  - mongo.yml
  - mongo-service.yml
  
  # Secrets
  - db-secret.yml
  - dashboard-secret.yml
  
  # SLD Services
  - sld-api-backend.yml
  - sld-api-backend-service.yml
  - sld-dashboard.yml
  - sld-dashboard-service.yml
  - sld-remote-state.yml
  - sld-remote-state-service.yml
  - sld-schedule.yml
  - sld-schedule-service.yml
  
  # Workers
  - sld-worker-default.yml
  - sld-worker-squad1.yml
  - sld-worker-squad2.yml
